// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/recipe-staging/Assist.tsx": () => import("../components/mockups/recipe-staging/Assist.tsx"),
  "./components/mockups/recipe-staging/CardGrid.tsx": () => import("../components/mockups/recipe-staging/CardGrid.tsx"),
  "./components/mockups/recipe-staging/Cockpit.tsx": () => import("../components/mockups/recipe-staging/Cockpit.tsx"),
  "./components/mockups/recipe-staging/Current.tsx": () => import("../components/mockups/recipe-staging/Current.tsx"),
  "./components/mockups/recipe-staging/PriorityInbox.tsx": () => import("../components/mockups/recipe-staging/PriorityInbox.tsx"),
  "./components/mockups/recipe-staging/Refined.tsx": () => import("../components/mockups/recipe-staging/Refined.tsx"),
  "./components/mockups/recipe-staging/TriagePanel.tsx": () => import("../components/mockups/recipe-staging/TriagePanel.tsx")
};
